name: Render documents and upload

on:
  workflow_dispatch:
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
    - uses: actions/checkout@v2

    - name: Render document
    	uses: lc5415/rmarkdown-action@v1
    	with:
    		input_file: scripts/Sample.Rmd
    		output_format: word_document
      - name: commit files
      run: |
    git config --local user.name "$GITHUB_ACTOR"
    git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
    git add -A
    git commit -m "Saving the results" || echo "no changes to commit"
    git push origin || echo "no changes to commit"
